//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordChecker.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthenticationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthenticationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordChecker.Resources.Language.AuthenticationResource", typeof(AuthenticationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTP (Authenticator App).
        /// </summary>
        public static string AuthType_GoogleAuthConfigurationRequirement {
            get {
                return ResourceManager.GetString("AuthType_GoogleAuthConfigurationRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKI.
        /// </summary>
        public static string AuthType_PkiConfigurationRequirement {
            get {
                return ResourceManager.GetString("AuthType_PkiConfigurationRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must not be empty.
        /// </summary>
        public static string ChangePasswordNoPassword {
            get {
                return ResourceManager.GetString("ChangePasswordNoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please repeat your new password.
        /// </summary>
        public static string ChangePasswordRepeatPassword {
            get {
                return ResourceManager.GetString("ChangePasswordRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the requested field type is not supported by the Password Checker. You cannot log in at the moment. Please create an issue in the GitHub repository..
        /// </summary>
        public static string FieldTypeNotSupported {
            get {
                return ResourceManager.GetString("FieldTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string FieldTypePassword {
            get {
                return ResourceManager.GetString("FieldTypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN.
        /// </summary>
        public static string FieldTypePin {
            get {
                return ResourceManager.GetString("FieldTypePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string FieldTypeToken {
            get {
                return ResourceManager.GetString("FieldTypeToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username for token.
        /// </summary>
        public static string FieldTypeTokenUsername {
            get {
                return ResourceManager.GetString("FieldTypeTokenUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password (repetition).
        /// </summary>
        public static string NewPasswordRepetition {
            get {
                return ResourceManager.GetString("NewPasswordRepetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition of the password is not correct.
        /// </summary>
        public static string NewPasswordRepetitionNotCorrect {
            get {
                return ResourceManager.GetString("NewPasswordRepetitionNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
