//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordChecker.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordChecker.Resources.Language.MainResource", typeof(MainResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key.
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the information for accessing your.
        /// </summary>
        public static string Description1 {
            get {
                return ResourceManager.GetString("Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instance to start the analysis of your saved passwords. The software is checking for duplicates, weak quality and the well known.
        /// </summary>
        public static string Description2 {
            get {
                return ResourceManager.GetString("Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service. No data is transferred or stored in any way. At the end, a report of all findings is generated..
        /// </summary>
        public static string Description3 {
            get {
                return ResourceManager.GetString("Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your logon data and press the &apos;Start check&apos; button..
        /// </summary>
        public static string EnterLogonData {
            get {
                return ResourceManager.GetString("EnterLogonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start check.
        /// </summary>
        public static string ExecuteCheck {
            get {
                return ResourceManager.GetString("ExecuteCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version ({0}) is available. Do you want to download it?.
        /// </summary>
        public static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available.
        /// </summary>
        public static string NewVersionTitle {
            get {
                return ResourceManager.GetString("NewVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server address (WebClient URI).
        /// </summary>
        public static string ServerAddress {
            get {
                return ResourceManager.GetString("ServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check passwords.
        /// </summary>
        public static string StepCheckPasswords {
            get {
                return ResourceManager.GetString("StepCheckPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count passwords.
        /// </summary>
        public static string StepCountPasswords {
            get {
                return ResourceManager.GetString("StepCountPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establish connection.
        /// </summary>
        public static string StepEstablishConnection {
            get {
                return ResourceManager.GetString("StepEstablishConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize.
        /// </summary>
        public static string StepFinish {
            get {
                return ResourceManager.GetString("StepFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load passwords.
        /// </summary>
        public static string StepLoadPasswords {
            get {
                return ResourceManager.GetString("StepLoadPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare report.
        /// </summary>
        public static string StepPrepareReport {
            get {
                return ResourceManager.GetString("StepPrepareReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Checker.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
