//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordChecker.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PdfFileResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PdfFileResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordChecker.Resources.Language.PdfFileResource", typeof(PdfFileResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access rights.
        /// </summary>
        public static string ApiKeyAccessRights {
            get {
                return ResourceManager.GetString("ApiKeyAccessRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access scopes.
        /// </summary>
        public static string ApiKeyAccessScopes {
            get {
                return ResourceManager.GetString("ApiKeyAccessScopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date (UTC).
        /// </summary>
        public static string ApiKeyExpiration {
            get {
                return ResourceManager.GetString("ApiKeyExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key information.
        /// </summary>
        public static string ApiKeyInfo {
            get {
                return ResourceManager.GetString("ApiKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breached count.
        /// </summary>
        public static string BreachedCount {
            get {
                return ResourceManager.GetString("BreachedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breached.
        /// </summary>
        public static string BreachedPageTitle {
            get {
                return ResourceManager.GetString("BreachedPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password identifier.
        /// </summary>
        public static string BreachedPasswordIdentifier {
            get {
                return ResourceManager.GetString("BreachedPasswordIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breached.
        /// </summary>
        public static string CheckBreached {
            get {
                return ResourceManager.GetString("CheckBreached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string CheckDatabaseName {
            get {
                return ResourceManager.GetString("CheckDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates.
        /// </summary>
        public static string CheckDuplicates {
            get {
                return ResourceManager.GetString("CheckDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string CheckDuration {
            get {
                return ResourceManager.GetString("CheckDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check finished at.
        /// </summary>
        public static string CheckEnd {
            get {
                return ResourceManager.GetString("CheckEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string CheckErrors {
            get {
                return ResourceManager.GetString("CheckErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields overview.
        /// </summary>
        public static string CheckFieldsOverview {
            get {
                return ResourceManager.GetString("CheckFieldsOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General information.
        /// </summary>
        public static string CheckGeneralInfo {
            get {
                return ResourceManager.GetString("CheckGeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string CheckQuality {
            get {
                return ResourceManager.GetString("CheckQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server address.
        /// </summary>
        public static string CheckServerAddress {
            get {
                return ResourceManager.GetString("CheckServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped fields.
        /// </summary>
        public static string CheckSkippedFieldsCount {
            get {
                return ResourceManager.GetString("CheckSkippedFieldsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check started at.
        /// </summary>
        public static string CheckStart {
            get {
                return ResourceManager.GetString("CheckStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total checked fields.
        /// </summary>
        public static string CheckTotalFieldsCount {
            get {
                return ResourceManager.GetString("CheckTotalFieldsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string CheckUserName {
            get {
                return ResourceManager.GetString("CheckUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection data.
        /// </summary>
        public static string ConnectionInfo {
            get {
                return ResourceManager.GetString("ConnectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following {0:N0} passwords are sharing the same value:.
        /// </summary>
        public static string DuplicatesHeading {
            get {
                return ResourceManager.GetString("DuplicatesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates.
        /// </summary>
        public static string DuplicatesPageTitle {
            get {
                return ResourceManager.GetString("DuplicatesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string DurationDays {
            get {
                return ResourceManager.GetString("DurationDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string DurationHours {
            get {
                return ResourceManager.GetString("DurationHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string DurationMinutes {
            get {
                return ResourceManager.GetString("DurationMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string DurationSeconds {
            get {
                return ResourceManager.GetString("DurationSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string ErrorsPageTitle {
            get {
                return ResourceManager.GetString("ErrorsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordChecker - Report.
        /// </summary>
        public static string Heading {
            get {
                return ResourceManager.GetString("Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string QualityGood {
            get {
                return ResourceManager.GetString("QualityGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong.
        /// </summary>
        public static string QualityStrong {
            get {
                return ResourceManager.GetString("QualityStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak.
        /// </summary>
        public static string QualityWeak {
            get {
                return ResourceManager.GetString("QualityWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string SummaryPageTitle {
            get {
                return ResourceManager.GetString("SummaryPageTitle", resourceCulture);
            }
        }
    }
}
