//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordChecker.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordChecker.Resources.Language.ReportResource", typeof(ReportResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breached.
        /// </summary>
        public static string Breached {
            get {
                return ResourceManager.GetString("Breached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of breached passwords.
        /// </summary>
        public static string BreachedCount {
            get {
                return ResourceManager.GetString("BreachedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can find a list of all passwords that were breached with the number of breaches. This information is loaded from.
        /// </summary>
        public static string BreachedDescription1 {
            get {
                return ResourceManager.GetString("BreachedDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - the check was executed by passing the first bytes of the hash of the password. The rest of the check was executed locally. No passwords were transferred in clear text!.
        /// </summary>
        public static string BreachedDescription2 {
            get {
                return ResourceManager.GetString("BreachedDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked fields.
        /// </summary>
        public static string CheckedFieldsCount {
            get {
                return ResourceManager.GetString("CheckedFieldsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check errors.
        /// </summary>
        public static string CheckErrors {
            get {
                return ResourceManager.GetString("CheckErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Findings: {0}.
        /// </summary>
        public static string DuplicateFindings {
            get {
                return ResourceManager.GetString("DuplicateFindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates.
        /// </summary>
        public static string Duplicates {
            get {
                return ResourceManager.GetString("Duplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of duplicate passwords.
        /// </summary>
        public static string DuplicatesCount {
            get {
                return ResourceManager.GetString("DuplicatesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of breaches.
        /// </summary>
        public static string NumberOfBreaches {
            get {
                return ResourceManager.GetString("NumberOfBreaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password identifier.
        /// </summary>
        public static string PasswordIdentifier {
            get {
                return ResourceManager.GetString("PasswordIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string QualityGood {
            get {
                return ResourceManager.GetString("QualityGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong.
        /// </summary>
        public static string QualityStrong {
            get {
                return ResourceManager.GetString("QualityStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak.
        /// </summary>
        public static string QualityWeak {
            get {
                return ResourceManager.GetString("QualityWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report was exported successfully. Do you want to open the file?.
        /// </summary>
        public static string ReportExportSucceeded {
            get {
                return ResourceManager.GetString("ReportExportSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as PDF.
        /// </summary>
        public static string SaveAsPdf {
            get {
                return ResourceManager.GetString("SaveAsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the target file for the report.
        /// </summary>
        public static string SelectExportFile {
            get {
                return ResourceManager.GetString("SelectExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped fields.
        /// </summary>
        public static string SkippedFieldsCount {
            get {
                return ResourceManager.GetString("SkippedFieldsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved.
        /// </summary>
        public static string SuccessfullySaved {
            get {
                return ResourceManager.GetString("SuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check report.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
