name: Build setup and release

on:
  push:
    tags:
      - 'v*.*'
      - 'v*.*.*'

jobs:
  build-setup:
    # Windows runner needs to be used for WiX builds
    runs-on: windows-latest

    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v4

    - name: 'Setup .NET8 SDK'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'

    - name: 'Add Syncfusion license to repo'
      id: prepare_build
      run: |
        # Remove the leading 'v' from the tag name to get the version
        $version = "${{ github.ref_name }}".Substring(1)
        Add-Content -Path $Env:GITHUB_OUTPUT -Value "buildVersion=$version"

        $filePath = "src/PasswordChecker.UI/App.xaml.cs"
        $content = Get-Content $filePath
        $newContent = $content.Replace("%LICENSE_KEY%", "${{ secrets.SF_LICENSE_KEY }}")
        Set-Content $filePath $newContent
      shell: powershell

    - name: 'Download SDK'
      run: |
        $url = "${{ secrets.NETWRIX_SDK_URL }}"
        $outputPath = "${{ runner.temp }}\sdk.zip"
        Write-Host "Downloading SDK from URL"
        Invoke-WebRequest -Uri $url -OutFile $outputPath
        Write-Host "SDK downloaded successfully"
      shell: powershell

    - name: 'Extract SDK'
      run: |
        $zipPath = "${{ runner.temp }}\sdk.zip"
        $extractPath = "C:\Dev\SDKs\Netwrix Password Secure\9.3.1.33994"
        
        # Create the target directory if it doesn't exist
        if (!(Test-Path $extractPath)) {
            New-Item -ItemType Directory -Path $extractPath -Force | Out-Null
        }
        
        # Extract the archive to the target directory
        Write-Host "Extracting SDK to: $extractPath"
        Expand-Archive -Path $zipPath -DestinationPath $extractPath -Force
        Write-Host "SDK extraction complete"
      shell: powershell

    - name: 'Build projects'
      run: |
        $version = ${{ steps.prepare_build.outputs.buildVersion }}
        & .\UpdateProjectVersion.ps1 -NewVersion $version
        dotnet build src/PasswordChecker.Setup/PasswordChecker.Setup.wixproj -c Release /p:Version=$version /p:AssemblyVersion=$version /p:FileVersion=$version /p:InformationalVersion=$version
      shell: powershell

    - name: 'Rename setups'
      run: |
        $version = ${{ steps.prepare_build.outputs.buildVersion }}

        $basePath = "src/PasswordChecker.Setup/bin/x64/Release/"

        # Rename the German setup
        $deFile = Get-ChildItem -Path "$basePath/de-DE/" -Filter "*.msi" | Select-Object -First 1
        if ($deFile) {
            $newName = "PasswordChecker-$version-de.msi"
            $newPath = Join-Path $deFile.DirectoryName $newName
            Write-Host "Renaming $($deFile.Name) to $newName"
            Rename-Item -Path $deFile.FullName -NewName $newName
        }

        # Rename the English setup
        $enFile = Get-ChildItem -Path "$basePath/en-US/" -Filter "*.msi" | Select-Object -First 1
        if ($enFile) {
            $newName = "PasswordChecker-$version-en.msi"
            $newPath = Join-Path $enFile.DirectoryName $newName
            Write-Host "Renaming $($enFile.Name) to $newName"
            Rename-Item -Path $enFile.FullName -NewName $newName
        }
      shell: powershell

    - name: 'Create GitHub release as draft'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Version ${{ github.ref_name }}
        files: |
          src/PasswordChecker.Setup/bin/x64/Release/de-DE/*
          src/PasswordChecker.Setup/bin/x64/Release/en-US/*
        draft: true
        body: |
          ## What's changed
          - Fill the content here

          **Full Changelog**: Insert link here
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}